// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqsleukaxvqjnssogkjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxc2xldWtheHZxam5zc29na2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjU2OTMsImV4cCI6MjA3MDg0MTY5M30.JqTpdkkD3xND46m0jpCcFMosjy7z1sa1Hvow3K7f5UM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});